version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql

    ports:
      - 3306:3306
    networks:
      - twotier
    restart: always 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-uroot","-proot"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s

  flaskapp:
    build:
      context: .
    container_name: flaskapp
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_DB: mydb 
    ports:
      - 5000:5000
    networks:
      - twotier
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s



volumes:
  mysql-data:
networks:
  twotier:
