services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - twotier
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql


  flask-app:
    build: .
    container_name: two-tier-app
    ports:
      - "5000:5000"
    networks:
      - twotier
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: devops
    depends_on:
      - mysql
    restart: always
    healthcheck: 
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  twotier:

volumes:
  mysql-data:
