apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:latest

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE   # ✅ FIX (important)
              value: "myDb"

          ports:
            - containerPort: 3306

          volumeMounts:
            - name: mysqldata
              mountPath: /var/lib/mysql

      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-pvc
